/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const GameResult = IDL.Record({
  'remainingScore' : IDL.Nat,
  'dartsThrown' : IDL.Nat,
  'timestamp' : Time,
  'playerName' : IDL.Text,
  'didWin' : IDL.Bool,
  'scoreSubmittedBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'getPlayerGames' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'getRecentGames' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'getResult' : IDL.Func([IDL.Nat], [GameResult], ['query']),
  'submitGame' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const GameResult = IDL.Record({
    'remainingScore' : IDL.Nat,
    'dartsThrown' : IDL.Nat,
    'timestamp' : Time,
    'playerName' : IDL.Text,
    'didWin' : IDL.Bool,
    'scoreSubmittedBy' : IDL.Principal,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'getPlayerGames' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'getRecentGames' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'getResult' : IDL.Func([IDL.Nat], [GameResult], ['query']),
    'submitGame' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };